### ISSUE TITLE
Add additional events for gcode execution

### ISSUE THREAD

**Issue by Faultier523** [smartin015/continuousprint#126]
It would be cool to add a possibility for a script when a filament change is required, for example to automatically move to a position and eject the filament.

**Comment by smartin015** [comment]
Agreed, that would be cool. I think I'll expose this after I've refactored script-running to be a bit more general, though... currently each script/event requires code and tests to be added in several places before they work. That's OK when there's only a couple scripts, but it seems like "on queue event, run script" is a recurring feature request :)

**Comment by smartin015** [comment]
With submission of #149, these events will be available to run scripts on in `v2.3.0` - release ETA is probably some time in December.
