### ISSUE TITLE
Not counting printed parts correctly.

### ISSUE THREAD

**Issue by Tony-321** [smartin015/continuousprint#157]
Plug in is not registering printed items and therefore not counting them correctly. No idea why.

It’s stating 3/15 items printed and printing No 4, while it’s actually printed 5 already and it’s currently printing the 6th, it did the same thing on the previous item in the que as well. Printed 3 more than i wanted.

no idea why.

![23FC01AF-CFD4-4F38-8946-BF5BA68B3B61](https://user-images.githubusercontent.com/118568388/202796282-6dbb02b6-4414-4306-979b-447dbfc571f0.jpeg)

it’s saying 
![1A0D1880-EA5B-4C3D-90BA-8B0623CEE113](https://user-images.githubusercontent.com/118568388/202796319-855c7a14-8d97-43c4-aa73-b26135a13f86.jpeg)

1. > 

- [ ]  @[](url)

**Comment by smartin015** [comment]
Hey @Tony-321 - thanks for the bug report. 

Can you please attach a sysinfo bundle so I can take a look at the plugin logs?

**Comment by smartin015** [comment]
@Tony-321 - I'm closing out this issue as I can't do anything for you without a sysinfo bundle to understand what's going wrong. If you find the time to submit one to this issue, I'll reopen it again to see what's up.

**Comment by Tony-321** [comment]
Hi mate, no problem.I upgraded my RaspberryPi and it seems to have resolved the issue.Perhaps an old PI can’t run the application correctly.Tony McCormackMHE Fleet Engineer.Mobile : 07841404332On 16 Dec 2022, at 13:48, Scott Martin ***@***.***> wrote:﻿
@Tony-321 - I'm closing out this issue as I can't do anything for you without a sysinfo bundle to understand what's going wrong. If you find the time to submit one to this issue, I'll reopen it again to see what's up.
