### ISSUE TITLE
increase or decrease print count with arrows.

### ISSUE THREAD

**Issue by leveos** [smartin015/continuousprint#19]
this is just a personal preference thing if it never happens it wont hurt.

But in a much older version of continuous print you could increase or decrease the print count with the click of some arrows. near the count value. something like what we use for the temperature control in Octopi would be a very clean solution as well.
![Screenshot 2022-03-15 183444](https://user-images.githubusercontent.com/78991214/158499299-f4cf8e93-33a7-43c5-9698-4bae735e959f.png)

i find that for one or two increases its faster than clicking the diolog box and typing the new value.

**Comment by smartin015** [comment]
I'm going to close this out as the UX has changed a lot in the last few releases, and it doesn't seem like anyone's interested in contributing the change. I also learned you can use the arrow keys to increment/decrement values, so maybe we can stick with that.
