### ISSUE TITLE
Plugin logo

### ISSUE THREAD

**Issue by smartin015** [smartin015/continuousprint#28]
It'd be neat to have a logo for the continuous print plugin - one that 

* is stylistically similar to OctoPrint's logo
* looks good when shown in the browser / on the plugin page
* can be tweaked to indicate whether the user is running on the beta branch (bragging rights!)

(Edit: also the new docs can be assigned a [header logo and favicon](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/))

**Comment by TylonHH** [comment]
Lets vote

**Comment by TylonHH** [comment]
![CP](https://user-images.githubusercontent.com/18073299/158913554-b28eae75-4a37-4b32-b621-4cf82aa0cc45.png)

**Comment by TylonHH** [comment]
![CP2](https://user-images.githubusercontent.com/18073299/158914662-714641a3-8c7e-4942-bb37-17a8c018d322.png)

**Comment by TylonHH** [comment]
![CP3](https://user-images.githubusercontent.com/18073299/158914918-2b08bea4-2dcc-4625-b87e-6ac8808cdeed.png)

**Comment by TylonHH** [comment]
![CP4](https://user-images.githubusercontent.com/18073299/158915098-ca0e8bb8-27a3-46a6-8921-ae35a4894c8a.png)

**Comment by smartin015** [comment]
I'm chatting now with a local, professional designer I've worked with in the past - they're interested in doing a commission for a custom icon, with a couple rounds of revision :)

I'd like the icon to be unique for the plugin, and pair nicely with OctoPrint's logo (to show where it came from). But if anyone has ideas I can pass them along, and post revisions here.

**Comment by TylonHH** [comment]
So something with an octopuss...

**Comment by aburtonProto** [comment]
![image](https://user-images.githubusercontent.com/93293241/159535006-af573d85-79f5-4aec-9cc5-ee52d2bd07e8.png)

Here is my contribution to the brainstorm.  Thank you MS Paint!

**Comment by smartin015** [comment]
As commissions usually go, this one ran a bit long. But IMO it was worth the wait!

I've mocked it up in situ in the docs, plugin tab and settings page:

![image](https://user-images.githubusercontent.com/607666/184986917-d0334e94-0507-4f30-b522-aa14e7d3e379.png)

![image](https://user-images.githubusercontent.com/607666/184987280-4fec956c-c13c-450a-80f6-6a3b7e679b9b.png)

![image](https://user-images.githubusercontent.com/607666/184987353-4cec0496-9b14-4f29-8aca-b3ff4fa23947.png)

What do y'all think? I also asked for a motion graphic so it'll animate on the docs page and on the titles of release videos, etc:

![CPQ](https://user-images.githubusercontent.com/607666/184987584-878630d2-5e2b-4c47-aa15-0e78cce3ce9e.gif)
