### ISSUE TITLE
Color & material type selection

### ISSUE THREAD

**Issue by smartin015** [smartin015/continuousprint#32]
**Is your feature request related to a problem? Please describe.**

Currently the queue chugs along assuming no manual intervention is needed, with all prints being the same color/material etc. Having the ability to recognize necessary color/material changes and do something about them would allow for even more autonomous printing.

**Describe the solution you'd like**

A solution that allows for

* A setting for default color and material to use for new items
* An extensible list of material types
* A way to manually assign the material used for a print
  * Bonus: Auto-assign material type of a gcode file based on a custom analysis queue.
* A setting for what gcode command to run when about to start a print with a different material (e.g. to park the head somewhere convenient, or even better to auto-change filament somehow)

**Describe alternatives you've considered**

* Just have a color wheel, selectable manually. This is fine, but basic. We can do better, probably.

**Additional context**

Can do some material inference:

1. Extend octoprint to allow plugins to add custom analysis queues (see [here](https://github.com/OctoPrint/OctoPrint/blob/027d8f8069b86a7f5e8c185a2d8f294b631c2f08/src/octoprint/server/__init__.py#L386))
2. Adapt the [GcodeAnalysisQueue](https://github.com/OctoPrint/OctoPrint/blob/027d8f8069b86a7f5e8c185a2d8f294b631c2f08/src/octoprint/filemanager/analysis.py#L365) implementation to search for identifying details within the file (e.g. from `processName` comments if sliced by Kiri:Moto)
3. Look up the details with [get_additional_metadata](https://docs.octoprint.org/en/master/modules/filemanager.html#octoprint.filemanager.storage.LocalFileStorage.get_additional_metadata)

**Comment by leveos** [comment]
this would be interesting to get working with the palette 2 or prusa MMU using the tool select in your slicer to automate different filaments.

**Comment by smartin015** [comment]
@leveos do you have one of those setups? I only have a single-extruder changed manually, so I'm going to need a beta tester to verify filament changing works well beyond just `@pause` for manual action.

**Comment by leveos** [comment]
i do have the palette 2. after sleeping on it im not sure it can be made to work since it has its own propriaty start up sequince. but perhaps with some gcode trickery I could bypass it. i will have to get it set back up one of these days and do some testing

**Comment by smartin015** [comment]
I suppose since palette allows for switching colors mid-print, it's driven by commands within the file - no need for a filament change action before the print starts, as long as the colors being used are already loaded.

Unless you want to use a different set of colors than what's loaded in the palette... but AFAIK nobody's developed an automatic changer for filament going *into* the palette. In any case, that would still benefit from this feature.

**Comment by smartin015** [comment]
I was recently pointed towards the [SpoolManager plugin](https://plugins.octoprint.org/plugins/SpoolManager/), which seems to be a very convenient base layer for this feature. 

* Its [API allows for filament selection](https://github.com/OllisGit/OctoPrint-SpoolManager/blob/master/octoprint_SpoolManager/api/SpoolManagerAPI.py#L451) and [fires an event](https://github.com/OllisGit/OctoPrint-SpoolManager/blob/master/octoprint_SpoolManager/api/SpoolManagerAPI.py#L251) which can be listened to.
* Data can be fetched as json allowing for a derived table of material types which can be used in a drop-down fashion.

```
http://printer_ip/plugin/SpoolManager/loadSpoolsByQuery?selectedPageSize=25&from=0&to=25&sortColumn=displayName&sortOrder=desc&filterName=&materialFilter=all&vendorFilter=all&colorFilter=all
```

**Comment by smartin015** [comment]
After some noodling on the UI side, here's what I've got so far:

![image](https://user-images.githubusercontent.com/607666/163722029-9014b6f9-ebc8-4f17-84de-606404010f20.png)

The little blocks are colored with the same color of the filament, and contain the first letter of the filament type (`P` for PLA, `A` for ABS, `T` for TPU, and so on). Naming conflicts (e.g. PLA and PETG) can be resolved case-by-case (PETG gets a `G` instead of a `P`). The number of extruders is inferred automatically based on the OctoPrint printer configuration.

Remaining work:

* [ ] Persisting filament selections
* [ ] Retrieving the list of filaments from SpoolManager
* [ ] Hiding elements if SpoolManager not installed
* [ ] Pausing the queue when filament changes are required / unpausing when change is completed.

**Comment by smartin015** [comment]
Implementation is now published to `1.6.0rc4`. Docs for the feature are available [here](https://smartin015.github.io/continuousprint/material-selection/).

@leveos, @aburtonProto - interested in giving this a try and providing some initial feedback?

**Comment by leveos** [comment]
I only have single extruder machines but i can dust off the pallet 2 and load up a couple spools and see how this functions between prints. it may just call extruder 1 and extruder 2 and tell the pallet the correct spool to use. but i wont have the time to fiddle untill the weekend.

**Comment by aburtonProto** [comment]
I am using on a single extruder machine as well.
The new features were properly hidden until I installed SpoolManager.  Print waits properly until I select a new spool.  Basic functionality seems to be working.  Nice work.

Small issue, when you add a new spool into SpoolManager, it does not show up as an option in the ContinuousPrint dropdown until you refresh the page.

**Comment by smartin015** [comment]
Neato. I'm going to move "material inference" into a separate issue (#54) and close this one out as "implemented enough" for now. Other aspects more relevant to distributed printing (i.e. #35) will be tackled there or in another issue.

@leveos I'm still interested in how the pallet handles the material selection code. If there's any special handling required, please open a new issue so we can chat about specific support - thanks!
