### ISSUE TITLE
Q: cycle behavior?

### ISSUE THREAD

**Issue by TylonHH** [smartin015/continuousprint#36]
Hi,
quick question. Let's say I wann print A and B five time each.
In wich order will it print?
1. A A A A A B B B B B
2. A B A B A B A B A B 

I only need the second option. Or an endless cycle option. With the second option I get sure to print complete sets (A+B).

kind regards

**Comment by smartin015** [comment]
If you:

1. Add A and B to the same job, each with count "1"
2. Set the job's count to "5"
3. Click "Start managing"

Then you should end up with order A B A B A B A B A B. If you're seeing different behavior, then there may be some bugs to work out. Can you confirm that works for you?

**Comment by TylonHH** [comment]
confirmed
