### ISSUE TITLE
ArcWelder plugin halts Continuous Print

### ISSUE THREAD

**Issue by TylonHH** [smartin015/continuousprint#42]
**Describe the bug**
suddenly don't work

**To Reproduce**
I added two files to the queue. And entered 10 in total. Later I added another 20 each.

**Expected behavior**
continus printing, afteer every file. When queue is finished it should run the end script

**System info:**
[octoprint-systeminfo-20220321150054.zip](https://github.com/smartin015/continuousprint/files/8316024/octoprint-systeminfo-20220321150054.zip)

**Additional context**
How can I debug this?

**Comment by smartin015** [comment]
Thanks for the report- I usually look at `octoprint.log` inside that zip file. 

One thing I notice right away is a lot of `Firing event: ZChange` debug details. I'm not sure where they come from, but they take up the majority of the log file. Filtering out a bunch of that (with `grep -v "Calling on\_event" octoprint.log | grep -v "ZChange" | grep -v "octoprint.events.fire" | grep -v "octoprint.events - DEBUG" | less`), I see when prints were queued and run, but no errors around it. 

I stripped the logs down to just those from the continuous print plugin (with `grep "octoprint.plugins.continuousprint" octoprint.log  | awk '{ printf "%s %s: %s\n", $1, $3, $4}' FS=" - "`): [this is the result](https://github.com/smartin015/continuousprint/files/8317481/out.txt)

Using `B` for bottom and `L` for lid, it looks like it went:

`BLBLBLBLB`

Then went inactive.

Then printed `BLB`. That's where the logs stopped.

Questions for you:

* Is the "inactive" point where you added more?
* Can you confirm that 
  * by "entered 10 in total" you set the count for the job?
  * by "later I added another 20 each" you changed the count for the job to 20?
 * How many prints finished before it stopped working?
 * Were there any errors, and what was the state of the printer when it stopped?

**Comment by TylonHH** [comment]
Because began to stutter because of high CPU load (RPi 3) I decided to disable all logging and to reboot the pi.
Then I added the two files again with 50 each.
Then I recognized some time later, that the printer stopped at the end of one piece. Nozzle on the top of the piece. Just right before the cleaning script should start. Still with heat nozzle and bed.
Here is s screenshot. In the top panel you can see the temperatures.
![grafik](https://user-images.githubusercontent.com/18073299/159428067-57440f06-882d-4e1d-95e2-e13a371128a4.png)
I wonder why it printed 8 times the 1st item, instead of BLBLBLB....
I also recognize some strange (misunderstood) behavior when I change the numbers. Are the number added or replaced with the given counters?
Unfortunately the printers sent no error in this state, otherwise Pushbullet would inform me immediately.

I going to start another job cycle. How should I "prepare" it, to get as much information you need? Logging?

**Comment by smartin015** [comment]
That's interesting. Just a shot in the dark - I wonder if the sheer volume of event logging is causing your raspi to slow down? I was having trouble actually parsing down to the logs I needed... and if you're using an SD card as a file system, excessive logging can cause weird behavior (e.g. [write wearing if the card doesn't have wear leveling](https://www.reddit.com/r/raspberry_pi/comments/ex7dvo/quick_reminder_that_sd_cards_with_wearleveling/)). 

Did you [edit logging.yaml](https://docs.octoprint.org/en/master/configuration/logging_yaml.html#changing-log-levels) or have serial logging enabled? Maybe try deleting those logs and disabling logging where possible.

I'd also really appreciate if you try again with all other plugins disabled - if it works, then continuous print may be interacting poorly with another plugin - but if it doesn't, then we can isolate the problems to just the continuous print plugin or octoprint/the printer itself.

**Comment by smartin015** [comment]
Hey @TylonHH, any luck?

**Comment by TylonHH** [comment]
I found out that one cause was a plugin which modify every new gcode automatically. So the bed cleaning script was catched and modified wich cause a loop or something. So I disabled this function.
But I still had another strange behavior. But I have to look closer. For me it's ok when you close this ticket.

**Comment by smartin015** [comment]
Thanks for the update - can you tell me the name of the plugin so I know to check for that on future issues?

**Comment by TylonHH** [comment]
> Thanks for the update - can you tell me the name of the plugin so I know to check for that on future issues?
https://github.com/FormerLurker/ArcWelderPlugin

**Comment by smartin015** [comment]
Thanks! Just reading through the description, the Arc Welder plugin creates differently named files with some changes.. The continuous print plugin tracks for the completion of the file it started (`cp_bed_clearing_script.gcode`), so I expect something AW is doing causes the CP plugin to lose its tracking.

There might be a way to keep things compatible. Mind sharing the ArcWelder config you're using? Or is it the default config?

**Comment by smartin015** [comment]
Closing for now - changes in `1.6.0` may have inadvertently fixed this.
