### ISSUE TITLE
keep getting Continuous Print API (Error 500) INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by sidneyns** [smartin015/continuousprint#78]
hello 

I have a couple of octopi installed on several raspberry pis and one of them keeps showing this error.  I have alredy tried to unistall and install several times, but no success 

any clues?

**Comment by smartin015** [comment]
Hey Sidney - thanks for the report, and sorry the upgrade wasn't a smooth one.

If you haven't already, you might try making a backup of the GCODE scripts in the plugin, then deleting plugin data using the eraser button in the plugin manager settings page:

![image](https://user-images.githubusercontent.com/607666/174603289-6eda53c8-812b-44ef-a9e1-6ebd821a4d3b.png)

But if you're able to before that - click the "System Info" button at the bottom of the settings dialog, then "Download Systeminfo Bundle" and attach it here. That contains various logs we can use to understand where the error is coming from.

**Comment by smartin015** [comment]
Hey @sidneyns, are you still having problems with this?

**Comment by sidneyns** [comment]
Hello my friend.. the new version fixed the issue

thank you

Sidney

**Comment by smartin015** [comment]
Great, thanks!

**Comment by craftking7** [comment]
Hi, i get the same error code when i try to start a print. I've already tried the method described here, but it didn't help. Any ideas?
[octoprint-systeminfo-20230906104759.zip](https://github.com/smartin015/continuousprint/files/12536539/octoprint-systeminfo-20230906104759.zip)
